spring:
  datasource:
    url: jdbc:h2:mem:blog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true

api:
  kakao:
    key: ${KAKAO_KEY}
    base-url: ${KAKAO_BASE_URL:https://dapi.kakao.com}
    path: ${KAKAO_PATH:/v2/search/blog}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    base-url: ${NAVER_BASE_URL:https://openapi.naver.com}
    path: ${NAVER_PATH:/v1/search/blog}
